---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      bundler-dev:
        patterns:
          - "parallel"
          - "pry"
          - "rake"
          - "rubocop-github"
          - "simplecov*"
        update-types:
          - "patch"
          - "minor"
      bundler-prod:
        patterns:
          - "*"
        exclude-patterns:
          - "parallel"
          - "pry"
          - "rake"
          - "rubocop-github"
          - "simplecov*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 20
    vendor: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"  # Group all GitHub Actions
    open-pull-requests-limit: 20
