inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Style/HashSyntax:
  Exclude:
    - spec/octofacts/util/keys_spec.rb
