#!/usr/bin/env bash

set -e
[ -z "$DEBUG" ] || set -x

echo 'Starting script/bootstrap'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

rm -rf "${DIR}/.bundle"

echo 'Running bundler'
bundle config set --local no_prune 'true'
bundle config set --local path 'vendor/bundle'
bundle install --local
bundle clean
bundle binstubs --force puppet pry rake rspec-core rubocop
chmod 0755 bin/octofacts-updater

echo 'Completed script/bootstrap successfully'
exit 0
