name: Integration Tests
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  integration-4_10_4:
    name: Integration Tests (Puppet 4.10.4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # v1.207.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run Integration Tests
        run: |
          bundle exec rake octofacts:spec:octofacts_integration
          local_integration_rspec=$?
          if [ "$local_integration_rspec" -ne 0 ]; then
            exit 1
          else
            exit 0
          fi
    environment:
      RSPEC_PUPPET_VERSION="2.6.15"
      PUPPET_VERSION="4.10.4"
  integration-7_30_0:
    name: Integration Tests (Puppet 7.30.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # v1.207.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run Integration Tests
        run: |
          bundle exec rake octofacts:spec:octofacts_integration
          local_integration_rspec=$?
          if [ "$local_integration_rspec" -ne 0 ]; then
            exit 1
          else
            exit 0
          fi
    environment:
      RSPEC_PUPPET_VERSION="3.0.0"
      PUPPET_VERSION="7.30.0"
