name: Integration Tests
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  integration-4_10_4:
    name: Integration Tests (Puppet 4.10.4)
    runs-on: ubuntu-latest
    env:
      RSPEC_PUPPET_VERSION: "2.6.15"
      PUPPET_VERSION: "4.10.4"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # v1.191.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run Integration Tests
        run: |
          bundle exec rake octofacts:spec:octofacts_integration
          local_integration_rspec=$?
          if [ "$local_integration_rspec" -ne 0 ]; then
            exit 1
          else
            exit 0
          fi
  integration-7_30_0:
    name: Integration Tests (Puppet 7.30.0)
    runs-on: ubuntu-latest
    env:
      RSPEC_PUPPET_VERSION: "5.0.0"
      PUPPET_VERSION: "7.30.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # v1.191.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run Integration Tests
        run: |
          bundle exec rake octofacts:spec:octofacts_integration
          local_integration_rspec=$?
          if [ "$local_integration_rspec" -ne 0 ]; then
            exit 1
          else
            exit 0
          fi
