name: Lint (Rubocop)
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@2a18b06812b0e15bb916e1df298d3e740422c47e # v1.203.0
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Lint with Rubocop
        run: |
          bundle exec rubocop --parallel
