name: Spec Tests (Rspec)
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  octofacts-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 # v1.195.0
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Test octofacts
        run: |
          bundle exec rake octofacts:spec:octofacts
      - name: Test octofacts_updater
        run: |
          bundle exec rake octofacts:spec:octofacts_updater
