name: Spec Tests (Rspec)
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  octofacts-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@bfefad842bb982ff05b233bcbc1571d97a87e69f # v1.206.0
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Test octofacts
        run: |
          bundle exec rake octofacts:spec:octofacts
      - name: Test octofacts_updater
        run: |
          bundle exec rake octofacts:spec:octofacts_updater
