name: Spec Tests (Rspec)
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  octofacts-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0 # v1.197.0
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Test octofacts
        run: |
          bundle exec rake octofacts:spec:octofacts
      - name: Test octofacts_updater
        run: |
          bundle exec rake octofacts:spec:octofacts_updater
