name: Spec Tests (Rspec)
on: [push, pull_request, workflow_dispatch]
jobs:
  octofacts-rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Test octofacts
        run: |
          bundle exec rake octofacts:spec:octofacts
      - name: Test octofacts_updater
        run: |
          bundle exec rake octofacts:spec:octofacts_updater
